import Head from "next/head";
import { useEffect } from "react";
import { useWebSocket } from "react-use-websocket/dist/lib/use-websocket";
import CardProfile from "../src/ui/components/card-profile";

export default function Home() {
  const { sendJsonMessage, lastMessage } = useWebSocket(
    process.env.NEXT_PUBLIC_AWS_WEBSOCKET_URL || ""
  );
  useEffect(() => {
    const user_id = localStorage.getItem("user_id") || "";
    sendJsonMessage({ action: "userSessionConnect", user_id: user_id });
  }, []);

  useEffect(() => {
    console.log(lastMessage);
  }, [lastMessage]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Homepage</h1>
        <CardProfile />
      </main>
    </>
  );
}
